version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: "typescript*"
      - dependency-name: "@types/node"
        versions: ["15.x"]
